project_name: kubectl-np-viewer
release:
  github:
    owner: runoncloud
    name: kubectl-np-viewer
builds:
  - id: kubectl-np-viewer
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - arm64
    - "386"
    ignore:
      - goos: windows
        goarch: arm64
    main: cmd/plugin/main.go  
archives:
  - id: kubectl-np-viewer
    builds:
    - kubectl-np-viewer
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
